Processing data in models
TEMESGEN-G25/blog-app pull request #2
Opened 2022-08-18 18:44 UTC by NatiG25

## Summary

### Create models
-  Create model classes for all entities as shown in the [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png).
-  Set up associations between models.

### Use models to insert data
- Familiarize yourself with ['rails c' command](https://guides.rubyonrails.org/command_line.html#bin-rails-console).
- Open rails console for your project.
- Create at least one user by running the following code:
    ```ruby
       first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')
       second_user = User.create(name: 'Lilly', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Poland.')
    ```
- Create at least 4 posts written by one of the users you created by running the following code:
    ```ruby
       first_post = Post.create(author: first_user, title: 'Hello', text: 'This is my first post')
    ```
- Create at least 6 posts comments for one of the posts you created by running the following code:
    ```ruby
       Comment.create(post: first_post, author: second_user, text: 'Hi Tom!' )
    ```
- Use other [CRUD methods](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/lessons/active_record_crud.md) to find, update and delete entities.

### Create custom methods
Your models should include some additional methods.
-  Users
    - A method that returns the 3 most recent posts for a given user.
-  Posts
    - A method that updates the posts counter for a user.
    - A method which returns the 5 most recent comments for a given post.
-  Comments
    - A method that updates the comments counter for a post.
-  Likes
    - A method that updates the likes counter for a post.

2022-08-18 19:06 UTC, mikethreels requested changes
Hi Nati, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 19:06 UTC, mikethreels commented on app/models/user.rb
> +  # has_many :likes, class_name: 'Like'
- [x] 2 of the associations are commented out please make sure to avoid this.
- [x] make sure to set the foreign key for each association.

2022-08-18 19:06 UTC, mikethreels commented on app/models/post.rb
> +
- [ ] a post should have many likes as well.

2022-08-18 19:06 UTC, mikethreels commented on app/models/user.rb
> +  end
- [ ] you are using the right code here, however, it is not in the right order. it should be something like `posts.order('created_at Desc').limit(3)`. the reason it should be like this is that in your code you are first taking 3 posts from the top of your list and after that, you are ordering these 3 posts by creation date. you should first order it to get the 3 most recent posts.

2022-08-18 19:06 UTC, mikethreels commented on app/models/post.rb
> +  end
- [ ] this is the same issue as when you're getting the 3 most recent post, you should first order the comments and after that, you should set the limit for the number of comments.

2022-08-18 19:14 UTC, NatiG25 commented
@mikethreels Thank you for your awesome suggestions. I'll implement them right away.

2022-08-18 19:50 UTC, mikethreels approved these changes
Hi Nati, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 22:23 UTC, merged

2023-03-22 04:37 UTC, NatiG25 commented
@mikethreels Thank you for your review.

![](https://media.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif)

**Note**: All optional & required changes have been implemented.